# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c71d7c9933feff209776758a9f5aad0454072b44402aa69651aa7d11618a5cd32327f54b3e67c3cef300bc785c4ae7bba935c6ef35d056f7368db5d43df5622b

test:
  secret_key_base: 2615bfd588e487cb95c6306e7b0c07dc5209c908438525922d5d6af2e907f3cfe55a02efee8cf1daa3e0a26fe6143966cdc8f70b843b332d1a6e690c1aa4f546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
